"""add_clarify_fields

Revision ID: ce14d0ccf533
Revises: 
Create Date: 2025-01-23 11:19:57.571960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce14d0ccf533'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('delegated_to', sa.String(), nullable=True))
    op.add_column('items', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('energy_level', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('estimated_time', sa.Integer(), nullable=True))
    op.alter_column('items', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('CAPTURED', 'CLARIFIED', 'DONE', 'DELEGATED', 'DEFERRED', name='itemstatus'),
               existing_nullable=True)
    op.alter_column('items', 'type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('UNDEFINED', 'TRASH', 'REFERENCE', 'SOMEDAY', 'PROJECT', 'NEXT_ACTION', 'WAITING_FOR', 'CALENDAR', name='itemtype'),
               existing_nullable=True)
    op.create_foreign_key(None, 'items', 'items', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.alter_column('items', 'type',
               existing_type=sa.Enum('UNDEFINED', 'TRASH', 'REFERENCE', 'SOMEDAY', 'PROJECT', 'NEXT_ACTION', 'WAITING_FOR', 'CALENDAR', name='itemtype'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.alter_column('items', 'status',
               existing_type=sa.Enum('CAPTURED', 'CLARIFIED', 'DONE', 'DELEGATED', 'DEFERRED', name='itemstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.drop_column('items', 'estimated_time')
    op.drop_column('items', 'energy_level')
    op.drop_column('items', 'project_id')
    op.drop_column('items', 'delegated_to')
    # ### end Alembic commands ###
